### ISSUE TITLE
需求：多平台兼容

### ISSUE THREAD

**Issue by lorki** [ffip/HiPerBridge#10]
注：考虑到 Linux 图形页面环境比较复杂， Linux 会不可避免地需要 GTK 等依赖（一般桌面系统版本都会自带）

- [x] Linux - Ubuntu（可能仅支持 20.04+ 版本）
- [ ] Linux - CentOS（可能会因为版本太旧无法使用）
- [ ] Linux - FreeBSD
- [ ] Linux - OpenBSD
- [ ] MacOS

**Comment by Steve-xmh** [comment]
Mac 需要蹲电脑到货（合掌）
Linux 支持下周再做

**Comment by lorki** [comment]
> 15 days ago

🤟

**Comment by ffip** [comment]
基本上已实现全兼容！
