### ISSUE TITLE
优化：新增启动后全网通告延迟提醒

### ISSUE THREAD

**Issue by lorki** [ffip/HiPerBridge#13]
启动后入网可能需要1~5分钟对本节点进行全网通告，
未收到通告的节点将可能无法连接到该节点。

因此在启动后，能够显示一条5分钟后消失的提醒消息：

正在全网通告节点在线状态，视网络情况预计可能需要1~5分钟，请耐心等待。

**Comment by Steve-xmh** [comment]
有点没听懂，补充一下吧

**Comment by lorki** [comment]
> 有点没听懂，补充一下吧

就像你下 磁力链接 文件一样

我做个种子，这个种子要通告到网络上，你才能知道我这个种子存在，才能通告磁力链接找到我。否则你就下载不了这个文件。

然而这个过程是需要一定时间的。

**Comment by Steve-xmh** [comment]
> > 有点没听懂，补充一下吧
> 
> 就像你下 磁力链接 文件一样
> 
> 我做个种子，这个种子要通告到网络上，你才能知道我这个种子存在，才能通告磁力链接找到我。否则你就下载不了这个文件。
> 
> 然而这个过程是需要一定时间的。

了解了

**Comment by Steve-xmh** [comment]
如果这个过程是可以从 HiPer 里检测并输出日志的话，建议在日志内输出类似信息来产生回调

**Comment by lorki** [comment]
启动后循环访问

http://6.0.0.6:8000/me

如果取到数据

基本上就是数据正常传输了

数据格式：

``` json
{
    "data": [
        {
            "exp": "2033-08-08",
            "owner": 2180860
        },
        {
            "exp": "2022-07-16",
            "owner": 6
        },
        {
            "exp": "2022-07-11",
            "owner": 1
        }
    ]
}
```

这里会展示之前拥有这个IP的用户id和过期时间，第一条为最新的拥有者和过期时间。

另外

从实时日志里面检测到第一跳
\>\>\> tun payload forward
也表明数据正常传输了

**Comment by lorki** [comment]
已解决
