### ISSUE TITLE
缺陷 无法捕获网卡初始化错误

### ISSUE THREAD

**Issue by lorki** [ffip/HiPerBridge#18]
错误信息：
{"level":"fatal","msg":"activate failed: Failed to find the tap device in registry with specified ComponentId 'tap0901', TAP driver may be not installed","time":"2022-08-03T20:56:43+08:00"}

**Comment by lorki** [comment]
不安装网卡且不存在wintun.dll将会遭遇该错误

**Comment by Steve-xmh** [comment]
考虑到HB会自行下载wintun/wintap，这个功能应该不太需要

**Comment by lorki** [comment]
ReOpen # 该问题已在客户端复现wintun不能启动需要手动去设置改wintun方式

Windows 10 家庭版 64bit

**Comment by lorki** [comment]
确认通过 #31 运行前对关键文件进行SHA1校验可有效避免该问题

**Comment by lorki** [comment]
该问题未再次复现。
