### ISSUE TITLE
需求：针对现有版本的优化与调整项

### ISSUE THREAD

**Issue by lorki** [ffip/HiPerBridge#2]
以下项按优先级进行排序

- [x] 如果网络启动成功，建议把密钥加密后保存到配置文件里面。然后凭证输入框内容变成8个⚪，如果启动从配置文件读到凭证，输入框就固定显示8个⚪。

- [x] 运行过程中可以点开小齿轮，只是网卡类型无法更改。(方便调整其它选项）

- [x] 设置项里面可以开启是否自动重启（遇到错误，类似守护功能）

- [x] 启动状态最好由颜色区分（例如 启动中为橙色，正在运行为绿色，错误为红色）

- [x] ip地址点击后复制到粘贴板（鼠标移动上去出现气泡提示：点击复制）

- [x] 启动位置居中

其它调整建议已通过QQ发送给@Steve-xmh。

**Comment by Steve-xmh** [comment]
已全部完成
