### ISSUE TITLE
需求 通过扩展套件局域网广播玩家远程服务器地址

### ISSUE THREAD

**Issue by lorki** [ffip/HiPerBridge#28]
*新增 通过扩展套件局域网广播玩家远程服务器地址 （免游戏内手动输入地址）
新模块发布地址 https://gitcode.net/to/hiper/-/tree/master/utils/minecraft-boradcast
例如远端玩家 6.6.9.9 开启游戏，使用端口26535 本地只需启动 mcb -addr 6.6.9.9:26535 即可完成局域网广播及登入（听说这样能离线使用）

**Comment by Steve-xmh** [comment]
一知半解（合掌）

**Comment by lorki** [comment]
该需求考虑通过 #29 ，作为插件实现。
