### ISSUE TITLE
需求 支持版本及完整性检测

### ISSUE THREAD

**Issue by lorki** [ffip/HiPerBridge#31]
避免下载非完整或客户端被感染或其它原因破损导致的故障和隐患，HiPer 现已将所有仓内文件进行sha1签名，详见目录内packages.sha1

https://gitcode.net/to/hiper/-/raw/master/packages.sha1

**Comment by Steve-xmh** [comment]
我寻思着之前叫换 HiPer Plus 的好像也是你
现在又要换回去也是你 😠
然后 HiPer 本体输出又和之前完全不一样了
又要重写一堆东西
（合掌）

**Comment by lorki** [comment]
> 我寻思着之前叫换 HiPer Plus 的好像也是你 现在又要换回去也是你 😠 然后 HiPer 本体输出又和之前完全不一样了 又要重写一堆东西 （合掌）

emmm如果只是判断内容是否存在来触发的话，好像改动不会多少？
