### ISSUE TITLE
MacOS 上的自动提权

### ISSUE THREAD

**Issue by Steve-xmh** [ffip/HiPerBridge#48]
几个参考链接：

- https://github.com/yichengchen/clashX/blob/master/ClashX/General/Managers/PrivilegedHelperManager.swift
- https://github.com/yichengchen/clashX/blob/master/ClashX/General/Managers/PrivilegedHelperManager+Legacy.swift
- https://ss64.com/osx/launchctl.html

**Comment by lorki** [comment]
为了解决不好操作的问题
 我写了个服务组件
hiper-service -service install
-service 有以下几个子参数 
start/stop/restart/install/uninstall
当然也支持通过 -config 指定配置文件

**Comment by lorki** [comment]
https://github.com/twitter/focus/blob/678202608bb3a36e2bdd8f7ab78333c42ed63660/focus/operations/src/maintenance/launchd.rs 参考实现

**Comment by lorki** [comment]
https://github.com/intecture/api/blob/f1b4e8d2a0f0ee522584967723a6217478288324/core/src/service/providers/launchctl.rs
https://github.com/edgedb/edgedb-cli/blob/79e1e8960fbb09a501049819793ad6420df0fda5/src/portable/macos.rs

---

最后一个是直接嵌入plist文件的

**Comment by lorki** [comment]
具体的plist文件已经提交pr了
