### ISSUE TITLE
通过对 HiPer 进程的 Stdin 发送指令优化停止和重载流程

### ISSUE THREAD

**Issue by ffip** [ffip/HiPerBridge#52]
通过STDIN主动停止及配置重载
hiper当前在启动后可向控制台输入
quit:主动停止
reload:配置重载

**Comment by Steve-xmh** [comment]
有没有一种可能，咱们是图形界面程序

**Comment by ffip** [comment]
> 有没有一种可能，咱们是图形界面程序

hiper本体更新了这个，意思是你可以。。。可能会用到？不是说hb要这样。。

**Comment by Steve-xmh** [comment]
那改一下标题吧，应该是优化关闭和重载流程
