### ISSUE TITLE
缺陷：启动时若有其它网卡与本网卡地址冲突，会导致网络不可访问。

### ISSUE THREAD

**Issue by lorki** [ffip/HiPerBridge#6]

**Comment by lorki** [comment]
HiPer Plus网段：6.0.0.0-7.255.255.255

**Comment by Steve-xmh** [comment]
这个问题是否应该由 HiPer 本身检测呢？

**Comment by lorki** [comment]
> 这个问题是否应该由 HiPer 本身检测呢？

因为hiper plus支持用户自定义ip的，所以本体检测不太好做。

**Comment by Steve-xmh** [comment]
因为 IP 地址是 HiPer 这边返回的，我也不能检测 IP 是否占用

**Comment by lorki** [comment]
那还是我来，我想想办法。

**Comment by lorki** [comment]
已解决
